name: 'Run automatic integration test of the Haskell project into Nixpkgs.'
description: Runs the integration and gives the result. Shows the state, predicts would the project's release to Hackage work inside Nixpkgs.
inputs:
  rev:
    description: 'Nixpkgs revision'
    required: False
    default: 'master'
runs:
  using: "composite"
  steps: 
    - name: "Install Cabal2Nix"
      run: nix-env -iA nixpkgs.haskellPackages.cabal2nix
      shell: bash
    - name: "Running the integration test"
      run: ${{ github.action_path }}/run-action.sh
      shell: bash
