name: 'Testing build inside Nixpkgs.'
description: |
  Imports the project Cabal description into the Nixpkgs store and runs a build inside Nixpkgs.
inputs:
  rev:
    description: 'Nixpkgs revision'
    required: False
    default: 'master'
runs:
  using: "composite"
  steps: 
    - name: "Install Cabal2Nix"
      run: nix-env -iA haskellPackages.cabal2nix
      shell: bash
    - name: "Running the integration test"
      run: ${{ github.action_path }}/run-action.sh
      shell: bash
