name: 'Run automatic integration test of the Haskell project into Nixpkgs.'
description: Gives the result of integration. Predicts would the project's release to Hackage work inside Nixpkgs.
inputs:
  rev:
    description: 'Nixpkgs revision'
    required: False
    default: 'master'
runs:
  using: "composite"
  steps:
    - name: "Install Nix-prefetch scripts"
      run: nix-env -f '<nixpkgs>' -Ai nix-prefetch-scripts
      shell: bash
    - name: "Install Cabal2Nix"
      run: nix-env -f '<nixpkgs>' -Ai haskellPackages.cabal2nix
      shell: bash
    - name: "Running the integration test"
      run: "${{ github.action_path }}/run-action.sh"
      shell: bash
